### PR TITLE
In response to issue #4

### PR DESCRIPTION
**Pull request by tidu090**
Hello @onosyoono 

Features of Calculator

1. Dark Mode
2. Clean and elegant UI
3. Material Design
4. Complex Expression Parsing
5. Power Function( i.e 2^4)
6. Square root
7. Decimal to Binary 
8. Decimal to Octal
9. Decimal to Hexadecimal
10. Log10
11. Natural Log
12. e^x
13. Sin 
14. Cos
15. Tan
16. Mod
____________________________________________________________________________

I hope you will appreciate my efforts and merge PR!
Have a nice day!

### CODE REVIEW

**Comment by onosyoono** [comment]
Thanks a lot for contributing

**Comment by uditswaroopa09** [comment]
My pleasure brother 
#keepFluttering

**Comment by uditswaroopa09** [comment]
Since you are planning to develop several apps it's my suggestion that you make different branches for the same repo.

**Comment by uditswaroopa09** [comment]
Hello @onosyoono can you please add the topic "hacktoberfest" in this repo, so that my PR can count for hacktoberfest as well
https://hacktoberfest-assets.nyc3.cdn.digitaloceanspaces.com/hacktoberfest-eligible-gif.gif

**Pull request merged**
